# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe4e2aca534ff75f6c6bf8cb65b276d2210f919a36b1b5f62ea4d6f88f9a9d4ad63e48e3afa621feb49d308d4b64e59b0ebc28b0d1065ea1901d3d449f08464

test:
  secret_key_base: 3eccba97952b16310a2f0f562b507f646190a4ec87cb86d8bac8597cf43a8b4a95976f5d3830e58d08f30836a117c52a364f2bc527aa888ff7097a5ff1f680fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
